site_name: Amethyst Documentation

repo_url: https://github.com/realms-developers/Amethyst.API/
repo_name: Amethyst.API on GitHub

theme:
  name: material
  palette:
    scheme: slate
    primary: purple
    accent: deep purple
  icon:
    logo: fontawesome/regular/gem
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          link: /Amethyst.Documentation/
          site_name: "Amethyst Documentation"
        - locale: ru
          name: Русский
          build: true
          link: /Amethyst.Documentation/ru/
          site_name: "Amethyst Документация"